/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./../src/components/home/about.vue')['default']
    BasicModal: typeof import('./../src/components/Modal/src/BasicModal.vue')['default']
    Button: typeof import('./../src/components/common/button.vue')['default']
    Collaboration: typeof import('./../src/components/home/collaboration.vue')['default']
    Cursor: typeof import('./../src/components/common/cursor.vue')['default']
    Footer: typeof import('./../src/components/common/footer.vue')['default']
    Header: typeof import('./../src/components/common/header.vue')['default']
    Hero: typeof import('./../src/components/home/hero.vue')['default']
    HeroImage: typeof import('./../src/components/home/hero-image.vue')['default']
    Layout: typeof import('./../src/components/common/layout.vue')['default']
    Menu: typeof import('./../src/components/common/menu.vue')['default']
    My_skill: typeof import('../src/components/home/thisskill.vue')['default']
    Myskill: typeof import('./../src/components/home/myskill.vue')['default']
    Nav: typeof import('./../src/components/nav/index.vue')['default']
    NutAvatar: typeof import('@nutui/nutui')['Avatar']
    NutButton: typeof import('@nutui/nutui')['Button']
    NutCard: typeof import('@nutui/nutui')['Card']
    NutCell: typeof import('@nutui/nutui')['Cell']
    NutCellGroup: typeof import('@nutui/nutui')['CellGroup']
    NutForm: typeof import('@nutui/nutui')['Form']
    NutFormItem: typeof import('@nutui/nutui')['FormItem']
    NutGrid: typeof import('@nutui/nutui')['Grid']
    NutGridItem: typeof import('@nutui/nutui')['GridItem']
    NutSwiper: typeof import('@nutui/nutui')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui')['SwiperItem']
    NutTabbar: typeof import('@nutui/nutui')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui')['TabbarItem']
    ProgressIndicator: typeof import('./../src/components/common/progress-indicator.vue')['default']
    Project_t: typeof import('./../src/components/common/project_t.vue')['default']
    Projects: typeof import('./../src/components/home/projects.vue')['default']
    ProjectT: typeof import('./../src/components/common/project-t.vue')['default']
    ProjectTile: typeof import('./../src/components/common/project-tile.vue')['default']
    Quote: typeof import('./../src/components/home/quote.vue')['default']
    RenderSkillColumn: typeof import('./../src/components/home/render-skill-column.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skills: typeof import('../src/components/home/thisskill.vue')['default']
    Timeline: typeof import('./../src/components/home/timeline.vue')['default']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarSpace: typeof import('@varlet/ui')['_SpaceComponent']
  }
}
